# Generated by Django 3.2.12 on 2023-06-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf2textapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
    ]
